/* ============================================================
   novedades.js — la lista de «Qué hay de nuevo» (fila 248,
   docs/NOVEDADES-AL-RECARGAR.md). Solo datos, lo más nuevo primero.
   `id`: el número de fila (o "248b" si una fila deja dos líneas);
   `texto`: una frase corta, con las palabras de la usuaria, sin
   nombres de ficheros ni de funciones. Cada fila que cambia algo
   visible añade su línea AL PRINCIPIO, en el mismo commit del código.
   Es un .js (no un JSON) para que valga también en la copia sin
   internet (file://), donde fetch de un JSON no funciona.
   ============================================================ */
window.NOVEDADES = [
  { id: '325', fecha: '2026-10-10', texto: 'El Gestor se pone al día solo al pulsar «Entrar». Con la aplicación abierta ya no sale la franja amarilla: junto al número de versión sale «hay versión nueva», y se puede pulsar.' },
  { id: '311', fecha: '2026-10-10', texto: 'Hay un tipo de asunto nuevo, «Certificado actividades extraescolares»: un solo certificado por profesor con todas sus actividades realizadas, y en cada una si organizó o acompañó.' },
  { id: '310', fecha: '2026-10-09', texto: 'En Herramientas hay una pantalla nueva, «Actividades extraescolares»: todas en una tabla, con filtros y hoja de cálculo, y se pueden apuntar las de cursos anteriores.' },
  { id: '309', fecha: '2026-10-09', texto: 'En la tarjeta «La actividad» hay un botón nuevo, «Avisar al claustro»: hace un informe en PDF con los datos de la actividad y el alumnado que va, por unidades, y abre el correo con el informe adjunto y el grupo del profesorado puesto en copia oculta. El grupo se elige en Ajustes → El centro. Si la lista cambia después, la tarjeta lo avisa y ofrece «Volver a avisar».' },
  { id: '322', fecha: '2026-10-09', texto: 'Cada plantilla de Word tiene un botón nuevo, «Retocar»: seleccionas un trozo del documento y lo cambias por otro texto, por un dato, o quitas el párrafo, sin salir de la aplicación. Vale para corregir una frase o una errata. «Cambiar por otro texto…» está también al convertir un documento en plantilla.' },
  { id: '321', fecha: '2026-10-09', texto: 'Una plantilla se puede dejar «Fuera de uso» desde Herramientas → «Plantillas»: sigue en la lista, en gris, pero deja de ofrecerse al generar un documento o al preparar un correo. Antes avisa de los hitos que la usan. Se vuelve a activar con un botón.' },
  { id: '320', fecha: '2026-10-09', texto: 'En Herramientas hay una pantalla nueva, «Plantillas», con todas las plantillas de Word y de correo juntas: se ve qué hitos usan cada una, y desde ahí se crean, se cambian, se les sustituye el fichero y se borran. Al crear una de Word ya se puede traer el fichero del ordenador, sin copiarlo antes a Dropbox.' },
  { id: '319', fecha: '2026-10-09', texto: 'En Herramientas → «Traer el alumnado» hay un recuadro nuevo, «Lo que tengo ahora»: dice de cuándo es cada fichero de alumnado y de personal, con su hora, cuántas personas trae, por dónde llegó y si hay otro más nuevo sin coger.' },
  { id: '318', fecha: '2026-10-09', texto: 'Al pulsar «Entrar», la aplicación pide también el permiso de las carpetas del alumnado, de la bandeja y del Centro de datos: ya no hay que volver a señalarlas cada mañana. En «Comprobación al entrar», el botón «Dar permiso» lo arregla con una pulsación.' },
  { id: '317', fecha: '2026-10-09', texto: 'El gestor ya distingue el personal docente del no docente y los cursos cuando trae los datos del Centro de datos.' },
  { id: '316', fecha: '2026-10-09', texto: 'La dirección del buzón de soporte se puede escribir una sola vez en el Centro de datos: la app la copia sola y en Ajustes sale con la nota «Se cambia en el Centro de datos».' },
  { id: '314', fecha: '2026-10-09', texto: 'En «Control del registro», la fecha «Revisar desde el día» ya deja escribir el año: se guarda al salir del campo o al pulsar Intro, y pregunta antes de quitar apuntes.' },
  { id: '313', fecha: '2026-10-09', texto: 'Los datos del centro y la firma de los correos se escriben una sola vez en el Centro de datos. La app los copia sola, y en Ajustes salen con la nota «Se cambia en el Centro de datos».' },
  { id: '312', fecha: '2026-10-09', texto: 'Si señalas la carpeta «CENTRO DE DATOS» en Ajustes → Este ordenador, al entrar la app coge sola los listados nuevos de Séneca (alumnado, personal, tutorías, Consejo Escolar y registro). Subirlos a mano sigue valiendo.' },
  { id: '306', fecha: '2026-10-08', texto: 'En «Nuevo asunto», con el tipo «Actividad extraescolar», sale «Apuntar la actividad»: eliges las unidades, desmarcas a quien no va y apuntas el profesorado. La ficha tiene una tarjeta «La actividad» con todo.' },
  { id: '308', fecha: '2026-10-08', texto: 'En el informe en PDF de «Exportar» puedes escribir el título. El fichero se guarda con ese mismo nombre.' },
  { id: '307', fecha: '2026-10-08', texto: 'El informe en PDF de «Exportar» ya no pierde asuntos al pasar de página, y «Imprimir» no saca una hoja de más.' },
  { id: '305', fecha: '2026-10-08', texto: 'El teléfono o el correo que apuntas en «El encargo» se ve ahora en la cabecera del asunto y de cada hito, con un botón para copiarlo. Si es un correo, sale ya marcado en «Para» al escribir un correo.' },
  { id: '303', fecha: '2026-10-08', texto: 'En Ajustes → Problemas, la app encuentra sola la carpeta de los asuntos que la habían perdido, también si está archivada, y los enlaza todos con un botón. «Buscar su carpeta» ya busca entre todas las carpetas.' },
  { id: '300', fecha: '2026-10-07', texto: 'Al cambiar el orden de los hitos de una guía, los asuntos abiertos recolocan los que están sin hacer.' },
  { id: '299', fecha: '2026-10-07', texto: 'El correo de un hito puede ir al tutor o tutora del grupo, y una plantilla puede adjuntar sola un documento.' },
  { id: '297', fecha: '2026-10-07', texto: 'Al guardar una guía, la biblioteca solo pregunta por lo que has cambiado, dice el hito y se puede cancelar.' },
  { id: '296', fecha: '2026-10-07', texto: 'Para formar un grupo puedes «Pegar una lista» de Séneca o de una hoja de cálculo.' },
  { id: '295', fecha: '2026-10-07', texto: 'En la lista de personas, «Enviar…» manda a todas su correo, y «Enviar un aviso…» lo hace sin documento.' },
  { id: '294', fecha: '2026-10-07', texto: 'Generar para todos enseña una muestra, deja el PDF de cada uno y reconoce los sellados de Séneca.' },
  { id: '293', fecha: '2026-10-07', texto: 'Un asunto puede ser de un grupo: ves a cada persona y qué se le ha generado, registrado y enviado.' },
  { id: '292', fecha: '2026-10-07', texto: 'En Problemas, los hitos de un asunto pueden volver a él, y se ve en qué se diferencian dos versiones.' },
  { id: '291', fecha: '2026-10-07', texto: 'En Ajustes → Problemas, cada aviso dice qué pasa, por qué y qué hacer. Inicio avisa con el número.' },
  { id: '290', fecha: '2026-10-07', texto: 'Un directivo puede dejar una nota, con documentos, en un asunto suyo; Administración la ve en Inicio.' },
  { id: '289', fecha: '2026-10-07', texto: 'Dirección, Secretaría y Jefatura hacen encargos desde la aplicación y ven en «Mis encargos» cómo van.' },
  { id: '288', fecha: '2026-10-07', texto: 'Ajustes tiene cuatro pestañas y un buscador. Las reparaciones de vez en cuando están en Herramientas.' },
  { id: '287', fecha: '2026-10-07', texto: 'En Ajustes → El centro hay una sección nueva, «Quién usa la aplicación», para decir quién es de Dirección, de Secretaría o de Jefatura de Estudios. Quien entra con uno de esos nombres ve solo Inicio y Archivo con los asuntos de su órgano, sin poder cambiar nada.' },
  { id: '286', fecha: '2026-10-06', texto: 'Al guardar un documento en un asunto que está en espera sale una casilla ya marcada, «Es lo que se esperaba. Termina la espera»: con ella el hito se da por hecho y el plazo siguiente empieza a contar. Y un hito de espera con el plazo vencido lleva el botón «No ha llegado nada».' },
  { id: '285', fecha: '2026-10-06', texto: 'En la pantalla de un hito hay un botón nuevo, «Hacer este hito»: genera el documento y guarda el PDF solo, espera a que dejes el PDF sellado en la carpeta (y lo reconoce sin preguntar) y deja el correo preparado con el documento adjunto. En Inicio sale «N listos para enviar».' },
  { id: '284', fecha: '2026-10-06', texto: 'La biblioteca de hitos trae los plazos legales ya puestos (y siete hitos comunes nuevos: requerir, audiencia, informe y la espera de cada uno), y los plazos se pueden contar en meses. Llegan solos al centro, una vez, y solo valen para los asuntos nuevos.' },
  { id: '282', fecha: '2026-10-06', texto: 'Un documento se puede quitar de su hito, o traer a otro, desde la pantalla de cualquier hito (el «⋯» de los documentos «De otros hitos» y «sin hito»). En la ficha, «Ninguno» pasa a llamarse «Quitar del hito». La tarea que se marcó sola con ese documento se queda marcada, con un aviso que deja desmarcarla.' },
  { id: '281', fecha: '2026-10-06', texto: '«Convertir en plantilla» vale también con un PDF que no tiene su Word: la app copia el texto y monta la plantilla con el membrete. Las tablas no se copian.' },
  { id: '280', fecha: '2026-10-06', texto: 'En el menú ⋮ de un documento Word hay una opción nueva, «Convertir en plantilla»: la app cambia sola los datos del asunto por su hueco, pone el membrete y te enseña el resultado junto al original antes de guardar.' },
  { id: '279', fecha: '2026-10-06', texto: 'Al crear un tipo de asunto o cambiarle el nombre, la app avisa si ya hay uno parecido o si ese era el nombre antiguo de otro, y deja usar el que hay o unirlos ahí mismo.' },
  { id: '278', fecha: '2026-10-06', texto: 'El informe en PDF de «Exportar» se puede agrupar por una o dos columnas: cada bloque lleva su título, su número de asuntos y la suma de sus importes.' },
  { id: '277', fecha: '2026-10-06', texto: 'Si un tipo de asunto es el nombre antiguo de otro, la app los une sola y lo dice. Y si dos tipos se parecen, lo avisa en Inicio para unirlos o decir que no son el mismo.' },
  { id: '276', fecha: '2026-10-06', texto: 'En «+ Añadir campo» de un asunto, un campo que el asunto ya tiene pero está vacío lleva el botón «Rellenar»: pide el valor ahí mismo. Y los botones apagados ahora se ven en gris.' },
  { id: '274', fecha: '2026-10-06', texto: 'En Ajustes de un tipo de asunto hay un apartado nuevo, «Al terminar el asunto»: sin abrirlo dice si el asunto se archiva o pasa a «Por liquidar». Ahí están ahora esa casilla y la de avisar a quien lo pide.' },
  { id: '270', fecha: '2026-10-06', texto: 'En el cuadro de Correo y en el de Séneca hay un botón nuevo, «Guardar como plantilla nueva»: convierte lo que has escrito en una plantilla, con los datos del asunto ya cambiados por su hueco.' },
  { id: '272', fecha: '2026-10-06', texto: 'En la ficha de un asunto, junto al nombre, se ven hasta 3 datos de la persona o empresa (para el alumnado, la unidad). Con «Elegir datos» decides cuáles, para todos los asuntos de esa clase.' },
  { id: '275', fecha: '2026-10-06', texto: 'Si el otro ordenador se queda el número mientras creas un asunto o guardas un documento, se crea con el siguiente y te lo dice; ya no hay que pulsar otra vez.' },
  { id: '271', fecha: '2026-10-06', texto: 'En el cuadro de Correo y en el de Séneca ya puedes elegir «Sin plantilla» y se queda. Si el tipo de asunto no tiene plantilla propia, el cuadro se abre sin plantilla.' },
  { id: '269', fecha: '2026-10-06', texto: 'Al avisar con el botón «Soporte», te pide tu correo una sola vez, para escribirte cuando tu aviso esté resuelto.' },
  { id: '267', fecha: '2026-10-05', texto: 'En la ficha de un asunto, junto a «+ Añadir documento», hay un botón «Generar documento» que te lleva al hito actual con sus plantillas ya a la vista.' },
  { id: '266', fecha: '2026-10-05', texto: 'Los datos de una empresa, o de cualquier tercero dado de alta a mano, se pueden cambiar desde la ficha del asunto. Si cambia el NIF o el nombre, las carpetas de sus asuntos abiertos y la suya del archivo cambian de nombre solas.' },
  { id: '265', fecha: '2026-10-05', texto: 'Si al archivar algún documento tiene un nombre demasiado largo para el archivo, la aplicación lo dice y deja acortarlo ahí mismo, en vez de fallar.' },
  { id: '263', fecha: '2026-10-05', texto: 'Un asunto ya no se queda sin crear porque su ruta salga larga: se crea igual y, si de verdad es muy larga, avisa en ámbar.' },
  { id: '259', fecha: '2026-10-02', texto: 'Herramientas → Control del registro: sube los listados de Séneca y mira qué apuntes no tienen asunto; Inicio avisa de los que faltan y de cuándo toca volver a subirlos.' },
  { id: '257', fecha: '2026-10-02', texto: 'Cambiar el asunto: el tipo se busca escribiendo, en una línea como el tercero, y el cuadro cabe entero en pantalla.' },
  { id: '260', fecha: '2026-10-02', texto: 'En un ordenador que trabaja sobre una copia de las carpetas se puede marcar «En este ordenador, solo consultar»: la aplicación no guarda nada ahí.' },
  { id: '255', fecha: '2026-10-02', texto: 'Campos de un hito: en la pantalla de cada hito hay «+ Añadir campo»; se rellenan ahí y salen también en la ficha, debajo del nombre de su hito.' },
  { id: '254', fecha: '2026-10-02', texto: 'En la ficha de un asunto, la tarjeta se llama ahora «Campos del asunto», con «+ Añadir campo» siempre a la vista; la ventana para elegir un campo es ancha y en columnas, y si algo falla al añadirlo, el aviso lo dice.' },
  { id: '256', fecha: '2026-10-02', texto: 'Al volver de una ficha a Inicio, la lista se queda exactamente a la misma altura, sin dar un saltito hacia abajo.' },
  { id: '253', fecha: '2026-10-02', texto: 'Los asuntos que cambias a un tipo que hay que liquidar, si ya no tienen nada por hacer, pasan solos a Por liquidar; también al marcar la casilla del tipo en Ajustes.' },
  { id: '252', fecha: '2026-10-01', texto: 'La ficha de una persona, en Personas y empresas, va ahora en tarjetas plegables con su resumen (familia, asuntos, matrícula, materias…); lo mismo sale en «Ver todo» dentro de un asunto.' },
  { id: '251', fecha: '2026-10-01', texto: 'Los campos ya no ofrecen «Añadir al nombre»: son etiquetas del asunto, salen en la ficha y al exportar.' },
  { id: '250', fecha: '2026-10-01', texto: 'Ajustes: para crear un tipo de asunto o de documento, primero se busca; si no está, se crea desde la misma caja.' },
  { id: '249', fecha: '2026-10-01', texto: 'Los asuntos que hay que liquidar (como el seguro escolar) pasan a la pestaña «Por liquidar» de Inicio, donde se marcan varios y se liquidan con su PDF.' },
  { id: '228', fecha: '2026-10-01', texto: 'Al cambiar o crear un hito desde un asunto, también se puede escribir su explicación, con viñetas.' },
  { id: '248', fecha: '2026-10-01', texto: 'Al entrar con una versión nueva sale esta ventana, «Qué hay de nuevo», y se vuelve a ver pulsando el número de versión de la barra lateral.' },
  { id: '247', fecha: '2026-10-01', texto: 'Los nombres de pila muy largos se acortan en los nombres de carpeta (el primero entero, los demás con su inicial).' },
  { id: '234', fecha: '2026-10-01', texto: 'Nuevo responsable de un hito: «Secretaría con V.º B.º de Dirección».' },
  { id: '233', fecha: '2026-10-01', texto: 'Un papel con sello se puede registrar como documento nuevo desde su aviso.' },
  { id: '245', fecha: '2026-10-01', texto: 'En la ficha de un asunto, «Datos del trámite» queda siempre a la vista.' },
  { id: '244', fecha: '2026-10-01', texto: 'Los campos de importe, número y fecha se escriben y se ven con el formato de siempre en España.' },
  { id: '243', fecha: '2026-10-01', texto: 'En Inicio, las pestañas y los títulos de la tabla se quedan fijos al bajar.' },
  { id: '238', fecha: '2026-10-01', texto: 'Ya se puede preparar el certificado de miembro del Consejo Escolar.' },
  { id: '236', fecha: '2026-10-01', texto: 'Un correo enviado desde la aplicación se guarda como PDF en el asunto.' },
  { id: '241', fecha: '2026-09-30', texto: 'Los asuntos de Inicio se pueden filtrar por fechas.' },
  { id: '240', fecha: '2026-09-30', texto: 'En el botón de soporte se puede escribir un texto largo, en un cuadro grande.' },
  { id: '239', fecha: '2026-09-30', texto: 'Los asuntos y documentos nuevos llevan un nombre fijo con su número.' },
  { id: '235', fecha: '2026-09-30', texto: 'Al aceptar un documento, la aplicación pregunta «¿Dónde se guarda?».' },
  { id: '232', fecha: '2026-09-30', texto: 'Los enlaces a la normativa llevan siempre al artículo.' },
  { id: '217', fecha: '2026-09-30', texto: 'El correo funciona aunque haya otra cuenta de Google abierta en el navegador.' },
  { id: '213', fecha: '2026-09-30', texto: 'Hay un botón de soporte para avisar de un fallo o proponer una mejora.' },
  { id: '227', fecha: '2026-09-29', texto: 'El botón «Ruta» copia la ruta normal de la carpeta.' },
  { id: '203', fecha: '2026-09-29', texto: 'La papelera se vacía sola a los 90 días.' }
];
